def Men_u():
    print("1 . add task")
    print("2 . show task")
    print("3 . Delet task")
    print("4 . Exit task")
    print("5 . Edit task")
    print("6 . Search task")
    print("7 . Fillter task")
    print("8 . Sort task")
    print("9 . undo task")
    print("10 . Redo task")
    print("11 . show summery task")
    print("12 . delete A few task")
    print("13 . Change A few task")
    print("14 . ShowedHistory")
    print("15 . add archive")
    print("16 . show command")